package com.AgentSaasAplication.notification.domain;

public enum NotificationType {
    MEMBERSHIP_INVITED,
    APPROVAL_REQUESTED,
    APPROVAL_APPROVED,
    APPROVAL_EXPIRED,
    APPROVAL_REJECTED,
    TASK_COMPLETED,
    TASK_FAILED,
    TERMINAL_SESSION_REQUESTED,
    TERMINAL_SESSION_APPROVED,
    TERMINAL_SESSION_REJECTED
}